version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql

  wordpress:
    build: ./
    image: wordpress:latest
    container_name: wp_sample
    depends_on:
      - db
    ports:
      - "1002:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
    volumes:
      - ./themes/wp_sample:/var/www/html/wp-content/themes/wp_sample
volumes:
    db-data:
